const btn = document.querySelectorAll('.button');
const canvas = document.querySelector('.canvas');

// ---------check RGB is rgb(255,255,255) or NOT---------
const rgbColorRegex = /rgb\(\d{1,3},\s*\d{1,3},\s*\d{1,3}\)/;

// ----------Convert RGB to hexCode function----------
const rgbToHex = (r, g, b) => {
    return `#${(1 << 24 | r << 16 | g << 8 | b).toString(16).slice(1)}`;
};

// forEach Loop all buttons...
btn.forEach((elm) => {
    elm.addEventListener('click', (e) => { // add Events... 
        // canvas.style.backgroundColor = `${e.target.id}`; 
        // canvas.style.backgroundColor = window.getComputedStyle(e.target).backgroundColor; // set background color...

        canvas.style.borderRadius = window.getComputedStyle(e.target).borderRadius;
        canvas.style.border = window.getComputedStyle(e.target).border;
        const rgb = window.getComputedStyle(e.target).backgroundColor; // get backgroundColor of target element...
        const match = rgb.match(rgbColorRegex); // match RGB color is rgb(255, 255, 255) or Not...

        // Change RGB to hex....
        if (match !== null) {
            const [r, g, b] = match[0].match(/\d{1,3}/g);
            console.log(`rgb(${r}, ${g}, ${b})`); // print RGB color...
            // convert RGB to HEX...
            const hexColor = rgbToHex(r, g, b); // Returns  hexcode like this "#0033ff"...
            canvas.style.backgroundColor = hexColor; // set HexCode BackgroundColor in Canvas...
            console.log(hexColor); // print HEX color...
        }

    });
});

