import Image from "next/image";

export default function Contact () {
    return (
        <div className="container size-1/2">
            <h1 className="bg-red-600 w-full  content-center text-center font-bold text-lg">This is Contact page Next JS</h1>
            <Image src="https://i.pinimg.com/736x/ea/ac/11/eaac112a3a7122b030195d2d5c52e211.jpg" alt="Audicar" width={800} height={800} quality={80}/>
        </div>
    );
}

export const metadata = {
    title: "Contact Page of Next App",
    description: "Generated by create next app",
};