export default function About () {
    return (
        <div>
            <h1 className="bg-red-600 h-screen content-center text-center font-bold text-lg">This is About next Js page</h1>
        </div>
    );
}

export const metadata = {
    title: "About Page of Next App",
    description: "Generated by create next app",
};